#Name of the application
spring:
  application:
    name: ZuulGateway

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#register url to server    

instance:
  hostname: localhost
  
server:
  port: 8762
  
zuul:
  prefix: /ecommerce
  routes:
    buyerService:
     path: /buyerService/**
    service-id: BUYERSERVICE
    sellerService:
     path: /sellerService/**
     service-id: SELLERSERVICE
    eurekaDiscoveryServer:
      path: /eurekaDiscoveryServer/**
      service-id: eurekaDiscoveryService

     
     
      