#Name of the application
spring:
  application:
    name: ZuulGateway

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#register url to server    

instance:
  hostname: localhost
  
server:
  port: 8762
  
zuul:
  prefix: /ecommerce
  routes:
    BuyerService:
     path: /buyerService/**
    service-id: BUYERSERVICE
    eurekaDiscoveryServer:
      path: /eurekaDiscoveryServer/**
      service-id: eurekaDiscoveryService
#    discountServer:
#      path: /discountServer/**
#      service-id: DISCOUNTSERVICE
#    eurekaDiscoveryService:
#      path: /eurekaDiscoveryService/**
#      service-id: EUREKADISCOVERYSERVICE

     
     
      